token:
  expiration_time: 86400000
  secret: '{cipher}AQBLm88k9IIYQsCKhPz22OyqsrsBoE9UH9BKj7e151o5T5ziOkosaH81rkZfxsKGinK0Cn2k9JOnzWFPWAlHQPEXmpS7Yu/yalNJA0WsOyRaPS392svI6qAkHAfdkFJltZYxVn9fCLRGZssj5pRZx176rybYF24oxlIuzpQojAw0uEcSjjEWgrypZ2dSYh5ccAqBY7zk7nzqXQW/LbrqXccnj97vYpmy9bPnUbyUEZQ34DYkkWcqoi4GwgCJvyIi/PhaBnjUh7+bnxz/wj/x59fDyfcY1hCWyv5Yr+n9DFv+HYRbca0IFEGkWLz+BElIak9KXoRh1OEmJY1ie6wDNO/Q1ZVMCLOWxWtZs2NIkNe/Odw0Pze+nNuvikerjTXuV0U='
