spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: '{cipher}AQBIn0NJqXU/hadZrcPtqp6SgP/t+N5KzYAlwnRBsEzC3CwjXqj7BqOgG6Z6mqliqH/MUATtxbKx5RWv66ylsML6vpUnO6PRzRX/LKDumGhfRgmdSxAqZv1RC010M37TVxTCXYN62NEW8C61epwbUZfHAmNh5jdwGnzOu5fXhqTPVNl7fSNtxWNMm8oVsWvP+DEXpVKZVygWOeh1i5nq3l5KIV6jNkrtWpACsanXJwOL4+5zIb1B14LNaCZmmLh1KVPH9JYWjQvBywTPgiojLcB0AeeWaA1OSav1H74imfEkfG1tHZK2CGMKmcHIUZG8ZkHS/44RyQ66RFue4Bjb18/uqfP9TMY+FfBHOB90perdYRsvIn/KhxvyfVU5kI1LN+c='


gateway:
  ip: 192.168.0.7

order_service:
  url: http://ORDER-SERVICE/order-service/%s/orders
