spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: '{cipher}AQBIn0NJqXU/hadZrcPtqp6SgP/t+N5KzYAlwnRBsEzC3CwjXqj7BqOgG6Z6mqliqH/MUATtxbKx5RWv66ylsML6vpUnO6PRzRX/LKDumGhfRgmdSxAqZv1RC010M37TVxTCXYN62NEW8C61epwbUZfHAmNh5jdwGnzOu5fXhqTPVNl7fSNtxWNMm8oVsWvP+DEXpVKZVygWOeh1i5nq3l5KIV6jNkrtWpACsanXJwOL4+5zIb1B14LNaCZmmLh1KVPH9JYWjQvBywTPgiojLcB0AeeWaA1OSav1H74imfEkfG1tHZK2CGMKmcHIUZG8ZkHS/44RyQ66RFue4Bjb18/uqfP9TMY+FfBHOB90perdYRsvIn/KhxvyfVU5kI1LN+c='

token:
  expiration_time: 86400000
  secret: '{cipher}AQBycInO6siXIw0RE07fVSzcAjwSvA5HMbeKfEfubOCuOkuWKVT1+QIcq2ugecOasSVXvm7JHQgmW6xUYg/6QSMgzH+TZHpVGF4gNO8JGNlkppv7i26nnKsipU7jH1XwtaI4hJAeIc5lhjT3p6WiioSkw6C59Xi97eo3c3gI41mxlj3+5cXkJQJpbzac2wSvlI04sTWAuiVVu7/wfpYkpUc0xj9iG1SQXhD06mlRjrF5xeqUtmQvMb7IkZvrV0DIyzhOZw5m/K2HGLJdLK9xTPOLEZ2E9Taf/YanlsbzMPnzQisQj+xdh7VJrAyQsR4DYze3F/dtv6dAFSop+E5gOq0ICqatqDThSoqxsLddAUg1yWQXq1Hi5xaVpE38PXfXFZySBZAlO5YfjTDqY+DOXYYD'

gateway:
  ip: 192.168.0.7
